const crimeActions = [
  "is committing acts of",
  "has been spotted engaging in",
  "is reportedly committing",
  "has committed",
  "is rumored to be committing",
  "was sighted committing",
  "was spotted committing",
  "is reportedly committing",
  "is plotting acts of",
  "is planning",
  "is plotting",
  "was discovered committing",
  "was caught committing",
  "is suspected of committing"
];

const genericCrimes = [
  ["perjury", "perjurer"],
  ["arson", "arsonist"],
  ["corruption", "corruptor"],
  ["larceny", "larcenist"],
  ["crime", "criminal"],
  ["hacking", "hacker"],
  ["phishing", "phisher"],
  ["phreaking", "phreaker"],
  ["injection", "injector"],
  ["theft", "thief", "thieves"],
  ["murder", "murderer"],
  ["terrorism", "terrorist"],
  ["activism", "activist"],
  ["protesting", "protestor"],
  ["forgery", "forger"],
  ["witchcraft", "witch", "witches"],
  ["vampirism", "vampire"],
  ["racketeering", "racketeer"],
  ["conspiracy", "conspirator"],
  ["immigration", "immigrant"],
  ["emigration", "emigrant"],
  ["espionage", "spy", "spies"],
  ["extortion", "extortionist"],
  ["embezzlement", "embezzler"],
  ["piracy", "pirate"],
  ["deviance", "deviant"],
  ["mutiny", "mutineer"],
  ["military desertion", "deserter"],
  ["burglarly", "burglar"],
  ["defamation", "defamer"],
  ["fraud", "fraudster"],
  ["impersonation", "impersonator"],
  ["assault", "assaulter"],
  ["jaywalking", "jaywalker"],
  ["loitering", "loiterer"],
  ["malfeasance", "malfeasant"],
  ["intoxication", "drunkard"],
  ["sabotage", "sabateur"],
  ["sedition", "seditor"],
  ["shoplifting", "shoplifter"],
  ["blackmail", "blackmailer"],
  ["profiteering", "profiteer"],
  ["smuggling", "smuggler"],
  ["blockade running", "blockade runner"],
  ["resistance", "resistance fighter"],
  ["vandalism", "vandal"],
  ["trespass", "trespasser"],
  ["treason", "traitor"],
  ["truancy", "truant"],
  ["tampering", "tamperer"],
  ["skimming", "skimmer"],
  ["slicing", "slicer"],
  ["splicing", "splicer"],
  ["cloning", "cloner"],
  ["treachery", "treacherer"],
  ["journalism", "journalist"],
  ["bombing", "bomber"],
  ["pollution", "pollutor"],
  ["littering", "litterer"],
  ["boosting", "booster"],
  ["politics", "politician"],
  ["running", "runner"],
  ["blasting", "blaster"],
  ["dancing", "dancer"],
  ["raving", "raver"],
  ["partying", "partier"],
  ["hashing", "hasher"],
  ["bruteforcing", "bruteforcer"],
  ["scripting", "script kiddie"],
  ["hijacking", "hijacker"],
  ["clickjacking", "clickjacker"],
  ["spoofing", "spoofer"],
  ["social engineering", "social engineer"],
  ["cache poisoning", "cache poisoner"],
  ["symlinking", "symlinker"],
  ["code execution", "code executor"],
  ["DDOSing", "DDOSer"],
  ["libel", "libeler"],
  ["regicide", "kingslayer"],
  ["deicide", "godslayer"],
  ["CamelCasing", "CamelCaser"],
  ["assassination", "assassin"],
  ["homicide", "killer"],
  ["omnicide", "omnikiller"],
  ["tyrannicide", "tyrantslayer"],
  ["xenocide", "xenoslayer"],
  ["raiding", "raider"],
  ["leaking", "leaker"],
  ["stim trafficking", "stimrunner"],
  ["juice trafficking", "juicerunner"],
  ["dust trafficking", "dustrunner"],
  ["spice trafficking", "spicerunner"],
  ["stim dealing", "stim slinger"],
  ["juice dealing", "juice dealer"],
  ["dust dealing", "dust dealer"],
  ["spice dealing", "spice dealer"],
  ["doppelganging", "doppelganger"],
  ["raiding", "raider"],
  ["mutation", "mutant"],
  ["experimentation", "experimenter"],
  ["manipulation", "manipulator"],
  ["surfing", "surfer"],
  ["spearphishing", "spearphisher"],
  ["keylogging", "keylogger"],
  ["hull breaching", "hull breacher"],
  ["airspace breaching", "airspace breacher"],
  ["running", "runner"],
  ["scavenging", "scavenger "],
  ["scrapping", "scrapper"],
  ["jacking", "jacker"],
  ["feeding", "feeder"]
];

module.exports = { genericCrimes, crimeActions };
