module.exports = [
  "Alert",
  "Warning",
  "Emergency Warning",
  "Take Precautions",
  "Take all necessary precautions",
  "Civilians are advised to take precautions",
  "Civilians are advised to take all necessary precautions",
  "Caution",
  "Be Advised",
  "Breaking",
  "Advisory",
  "Emergency Advisory",
  "Emergency Alert",
  "Critical Advisory",
  "Update",
  "Citizens are advised to be on alert",
  "Citizens are advised to take caution",
  "Citizens, be advised",
  "Citizens, take caution",
  "Citizens, be on alert",
  "All MegaCity citizens are to be advised",
  "All MegaCity citizens, be advised",
  "MegaCity citizens, take caution",
  "All civilians are advised to be on alert",
  "Public Alert",
  "MCPD Advisory",
  "MCPD Alert",
  "MCPD Emergency Alert",
  "MCPD Breaking Alert",
  "Metropolitan alert",
  "Metropolitan advisory",
  "Regional emergency alert",
  "Regional emergency advisory",
  "Regional alert",
  "Regional advisory",
  "Regional warning",
  "Press advisory",
  "News advisory",
  "Media advisory",
  "Mandatory alert",
  "Special advisory",
  "Special warning",
  "Special advisory",
  "Monitoring situation",
  "Developing situation",
  "Developing news"
];
