// nounArray contains singular nonproper nouns.
// They may appear in any title except Action of Proper.

module.exports = [
  "Empire",
  "Jedi",
  "Menace",
  "Sith",
  "Force",
  "Womp Rat",
  "High Ground",
  "Galaxy",
  "Hutt",
  "Bantha Fodder",
  "Trade Federation",
  "Republic",
  "Gungan",
  "Alliance",
  "Confederacy",
  "Vulcan",
  "Fleet",
  "Rebellion",
  "Lightsaber",
  "Dark Jedi",
  "Knight",
  "Order",
  "Prophecy",
  "Chosen One",
  "Resistance",
  "Senate",
  "Star Forge",
  "Trade Negotiation",
  "Wampa",
  "Bantha",
  "Holiday Special",
  "Battlestation",
  "Queen",
  "Emperor",
  "Chancellor",
  "Asteroid Field",
  "Nerf Herder",
  "Moof-Milker",
  "Spy",
  "Moisture Farm",
  "Bounty Hunter",
  "Senator",
  "Smuggler",
  "Wookiee",
  "Scavenger",
  "Stormtrooper",
  "Clone Trooper",
  "Kessel Run",
  "Gundark",
  "Rathtar",
  "Traitor",
  "Spirit",
  "Master",
  "Apprentice",
  "Commander",
  "Smuggler",
  "Threat",
  "Droid",
  "Fuzzball",
  "Ice Cream Maker",
  "Furball",
  "Twerp",
  "Swindler",
  "Melted Helmet",
  "Wild Bantha Chase",
  "Walking Carpet",
  "Gonk Droid",
  "Cantina Band",
  "R2 Unit",
  "BB Unit"
];
