const companySuffixes = [
  `Logistics`,
  `& Sons`,
  `Finance`,
  `Deuterium`,
  `Heavy Industries`,
  `Industries`,
  `Capital`,
  `Global`,
  `Systemwide`,
  `Pan-Sector`,
  `Galactic`,
  `Holding`,
  `Heavy Extraction & Manufacturing`,
  `Pharmaceuticals`,
  `Energy Extraction`,
  `Celestial Object Capture & Extraction`,
  `Investment`,
  `Financial Services`,
  `Strategic Holdings`,
  `Strategic Security`,
  `Security`,
  `Paramilitary Security`,
  `Cryopreservation`,
  `Bionics`,
  `Robotics`,
  `Robotics & Bionics`,
  `Cyber-Augmentation`,
  `Robo-Augmentation`,
  `Neuro-Augmentation`,
  `Nootropics`,
  `Neuro-Extraction`,
  `Private Law Enforcement`,
  `Private Security`,
  `Private Military Services`,
  `Private Military Contracting`,
  `Consulting`,
  `Strategic Consulting`,
  `Mergers & Acquisitions`,
  `Private Corporate State`,
  `Multimedia Protocol`,
  `Distributed Republic`,
  `Neurotheological`,
  `Neuroscientific`,
  `Quantum Cryptography`,
  `Militarized Police Services`,
  `Transhuman Bionics`,
  `Augmented Reality Engineering`,
  `Engineering`,
  `Quantum Engineering`,
  `Space Engineering`,
  `Interstellar Engineering`,
  `Astroengineering`,
  `Astronautics`,
  `Biodata`,
  `Data`,
  `Exobiology`,
  `Exoarchaeology`,
  `Exozoology`,
  `Electronic Telepathy`,
  `Survelliance`,
  `Neural Implantation`,
  `Synthfood Production`,
  `Wetware Engineering`,
  `Cybermedical Manufacturing`
];

const companyTypes = [
  `Group`,
  `Group`,
  `Group, Ltd.`,
  `Company`,
  `MegaCorp`,
  `Megacorporation`,
  `Corporation`,
  `Corporation, Ltd.`,
  `Conglomerate`,
  `Partners`,
  `Partners`
];

module.exports = { companySuffixes, companyTypes };
