const qualifiers = [
  "A safe and effective",
  "An FCPS-approved",
  "A federally-approved",
  "A clinically proven"
];

const types = [
  "pill",
  "pill",
  "eyedrop",
  "inhaler",
  "suppository",
  "insufflation",
  "firmware patch",
  "cybernetic implant"
];

const frequencies = [
  "once-daily",
  "daily",
  "once-weekly",
  "weekly",
  "monthly",
  "annual",
  "biannual"
];

const conditions = [
  "reduce the risk of Z Virus infection",
  "control symptoms of Z Virus infection",
  "control symptoms of cybernetic limb incompatibility",
  "reduce the risk of transdimensional attacks",
  "shield your thoughts from being read by psionics",
  "reduce the risk of mind hacking",
  "treat symptoms of alien egg implantation",
  "treat symptoms of psionic attack",
  "treat symptoms of transdimensional attack",
  "prevent acute radiation syndrome",
  "eliminate the need to sleep",
  "treat the symptoms associated with permanent immersion in virtual reality",
  "scramble neural scanners",
  "prevent accurate retinal scans",
  "prevent unexpected local gravity distortion",
  "prevent unexpected local time distortion",
  "prevent unexpected transdimensional phasing",
  "control symptoms of exposure to the vaccuum of space",
  "control side effects associated with unexpected local gravity distortion",
  "control side effects associated with unexpected local time distortion",
  "control side effects associated with unexpected transdimensional phasing"
];

const sideEffectsNormal = [
  "blurred vision",
  "nausea",
  "stomach bleeding",
  "trouble sleeping",
  "constipation",
  "skin rash",
  "dermatitis",
  "diarrhea",
  "dizziness",
  "drowsiness",
  "dry mouth",
  "headache",
  "insomnia",
  "mania",
  "depression",
  "new or worsening depression",
  "allergic reaction",
  "fever",
  "pain",
  "skin reactions",
  "a feeling of unwellness",
  "fatigue",
  "hair loss",
  "mouth sores",
  "lower blood cell count",
  "swelling",
  "sore skin",
  "drop in fertility",
  "drop in sex drive",
  "alopecia",
  "loss of appetite",
  "difficulty swallowing",
  "yellow-red irises",
  "whitening of the hair",
  "tinnitus",
  "prickling sensations on the skin",
  "hearing a low humming sound",
  "ear vibration",
  "increased fingernail and hair growing speed",
  "lengthening of canine teeth",
  "tooth tenderness",
  "toothache",
  "mild backache",
  "throbbing of hands or feet",
  "uncontrollable twitching",
  "sudden sleepiness",
  "nosebleed",
  "coughing",
  "agitation around cats",
  "cravings for fish",
  "anxiety",
  "mood swings",
  "irritability",
  "confusion",
  "difficulty concentrating",
  "feeling disconnected or numb",
  "elevated blood pressure",
  "racing heartbeat",
  "being startled easily",
  "edginess",
  "agitation",
  "muscle tension",
  "problems with memory",
  "low hard drive space",
  "reduced CPU power",
  "visual snow",
  "hardware compatibility issues",
  "interface port compatibility issues",
  "elevated fear of transdimensional attacks",
  "elevated fear of psionic attacks"
];

const sideEffectsWild = [
  "transdimensional phasing",
  "total organ failure",
  "cybernetic limb glitches",
  "growing gills",
  "blue or purple skin",
  "radical genetic mutation",
  "manifestation of superpowers",
  "growing bat wings",
  "sudden teleportation",
  "phasing through matter",
  "sudden extra limbs",
  "ability to move objects by thinking",
  "ability to hear the thoughts of others",
  "ability to project lightning from fingertips",
  "destructive beams of energy emanating from the eyes",
  "new or worsening mutant powers",
  "extreme leg lengthening",
  "taking on a wolf-like appearance",
  "sudden lycanthropy during full moons",
  "the emergence of tentacles from the torso",
  "the ability to bend space and time at will",
  "local gravity distortion",
  "spontaneous time reversal",
  "gradual transformation into an alien lobster",
  "infestation by an incorporeal malevolent entity",
  "a pair of large red horns growing from the forehead",
  "emergence of bat wings from the shoulder blades",
  "the ability to breathe fire",
  "the ability to turn objects to ice by touching them"
];

const prefixes = [
  "super",
  "ultra",
  "hyper",
  "dia",
  "post",
  "contra",
  "omni",
  "pan",
  "circum",
  "peri",
  "dys",
  "ante",
  "pre",
  "pro",
  "inter",
  "ambi",
  "amphi",
  "quad",
  "tetra",
  "bene",
  "eu",
  "semi",
  "hemi",
  "pro",
  "intra",
  "endo",
  "macro",
  "multi",
  "poly",
  "epi",
  "uni",
  "mono",
  "ex",
  "extra",
  "extro",
  "ecto",
  "exo",
  "hypo",
  "ego",
  "auto",
  "uth",
  "micro",
  "tri",
  "sub",
  "hypo",
  "com",
  "con",
  "sym",
  "syn",
  "intra",
  "endo",
  "quenta",
  "quanta",
  "zam",
  "vico",
  "din",
  "norco",
  "xo",
  "amox",
  "dela",
  "sona",
  "soma",
  "lipi",
  "gluco",
  "neuron",
  "tin",
  "mo",
  "trin",
  "abili",
  "fy",
  "humi",
  "ra",
  "cres",
  "tor",
  "vair",
  "ad",
  "en",
  "brel",
  "neu",
  "lasta",
  "lan",
  "tus",
  "oxy",
  "con",
  "co",
  "don"
];

module.exports = {
  qualifiers,
  types,
  frequencies,
  conditions,
  sideEffectsNormal,
  sideEffectsWild,
  prefixes
};
