const dangerStates = [
  "mutant",
  "bloodthirsty",
  "pandimensional",
  "solar",
  "homicidal",
  "dimensional",
  "stim-addled",
  "lunar",
  "plague-infested",
  "gene-enhanced",
  "bio-enhanced",
  "elemental",
  "zombified",
  "cybernetic-enhanced",
  "mech-enhanced",
  "psychic-enhanced",
  "superpowered",
  "mecha-armored",
  "exiled",
  "foreign",
  "ancient",
  "evil",
  "amoral",
  "Cthulhu-worshipping",
  "Martian",
  "Venusian",
  "Plutonian",
  "extradimensional",
  "extrasolar",
  "extragalactic"
];

const dangerGroups = [
  "gang",
  "pack",
  "band",
  "caravan",
  "cargo ship",
  "battlegroup",
  "battlefleet",
  "sector fleet",
  "invasion fleet",
  "patrol ship",
  "division",
  "faction",
  "freighter",
  "mining vessel",
  "hovertransport",
  "battlegang",
  "war party",
  "group",
  "band",
  "batch",
  "guild",
  "society",
  "trade association",
  "battalion",
  "platoon",
  "cabal",
  "fringe movement",
  "splinter group",
  "splinter cell",
  "group",
  "cell",
  "cult",
  "religious cult",
  "demonic cult",
  "bloodgang",
  "colony ship",
  "teletransport",
  "skytaxi",
  "horde",
  "battlecarrier",
  "tank division",
  "militia faction",
  "political party",
  "religious sect",
  "sectarian faction",
  "tribe",
  "resistance group",
  "secret order",
  "pair",
  "dark order",
  "ship",
  "transport",
  "frigate",
  "blockade runner",
  "resistance movement",
  "guerilla faction",
  "fleet"
];

module.exports = { dangerStates, dangerGroups };
