module.exports = [
  "in Sector 0.3",
  "in Sector 8756-Delta",
  "in Sector 9450",
  "in Sector 6477",
  "in Null Sector",
  "in Sector 2436",
  "in Sector 3478",
  "in Sector 701",
  "in Sector 972",
  "in Echo Sector",
  "in Sector 6903",
  "in Sector 9834",
  "in Sector 7",
  "in Sector 127.0.0.1",
  "in Sector 64a5",
  "in Sector 86",
  "in Sector AA23",
  "in Sector 1138",
  "in Undefined Sector",
  "in Error Sector",
  "in NaN Sector",
  "in Segfault Sector",
  "in the missing sector",
  "in the drowned sectors",
  "in the lost sectors",
  "in every sector",
  "in Sector 327",
  "in the Irradiated Sector-Chain",
  "in the Far Northern Sector-Chain",
  "in NullSec",
  "in Sub-Tropical Sector-Chain B",
  "in the Grey Sector-Chain",
  "in the Pacific Sector-Chain",
  "in the Crumbling Sector-Chain",
  "in the Lost Sector-Chain Array",
  "across the Pan-Continental Sector-Chain Array",
  "in the outer deathwastes",
  "in the near deathwastes",
  "in the Underspyre",
  "in the Midspyre",
  "in the Upper Spyre",
  "in the Far-Upper Spyrepoint",
  "in the hive depths",
  "in the far-deep hive levels",
  "deep in the lower levels",
  "in the far undersewers",
  "in the Mutant Caverns",
  "in the spice mines of Kessel",
  "in near Earth orbit",
  "at the South Pole Colony",
  "in low Earth orbit",
  "at the solarside Lagrange point",
  "in the exoatmosphere",
  "on a stratospheric airplatform",
  "on the virtuanet",
  "on the holonet",
  "on the internet",
  "at a New Delhi holocafe",
  "at the World War IV Memorial",
  "aboard Satellite Station Delta",
  "in orbit over Mars",
  "in Second Life 3",
  "outside the Western Mars Airlock",
  "near the Southern Mars Airlock",
  "on the outernet",
  "on the ethernet",
  "on the starnet",
  "on the spacenet",
  "on the cybernet",
  "on the echonet",
  "on the metanet",
  "on the tetranet",
  "on the synthnet",
  "on the tachyonet",
  "on the etherweb",
  "on the starweb",
  "on the spaceweb",
  "on the cyberweb",
  "on the echoweb",
  "on the metaweb",
  "on the tetraweb",
  "on the synthweb",
  "on the tachyoweb",
  "on the darknet",
  "on the darkweb",
  "inside the darkmind",
  "in the MagmaCore Colonies",
  "on Titan Colony 7",
  "in the distant past",
  "in the far future",
  "six weeks in the future",
  "in the year 432",
  "on Level 2346",
  "on Level 834",
  "on Level 61",
  "on Levels 663 through 669",
  "in Sector 84, Level 312",
  "in Sector 6008, Level 5",
  "on Level 3425",
  "on Level 8214",
  "on Level 93",
  "somewhere near Level 106",
  "around Level 938",
  "on Levels 3301 through 3315",
  "in the sewers near Level 239",
  "in Sector 7654, Level 48",
  "in Sector 124, Level 9469",
  "on Level 435",
  "on Level 610",
  "on Level 9380",
  "somewhere near Level 784",
  "around Level 7701",
  "on Levels 9987 through 10004",
  "near Level 897",
  "in Sector 3457, Level 9386",
  "in Sector 9854, Level 3256",
  "in the cloud tradelanes",
  "in the stratospheric tradelanes",
  "in the orbital tradelanes",
  "in the underdark",
  "in an alley in the underhive",
  "in an undersewer cavern",
  "inside a Net Fortress",
  "in a netcavern",
  "beneath the Artificial Ice Cap",
  "in Neo Chernobyl",
  "in eastern NeoTokyo",
  "in a Wakandan mine",
  "in the Kuiper Belt",
  "in the chaos dimension",
  "from the lair of the Undersewer King",
  "near the White House",
  "beneath the ruins of San Francisco",
  "in what was once New York",
  "beyond the time border",
  "in the fourth dimension",
  "in the second dimension",
  "aboard a starcarrier",
  "aboard a solar freight hauler",
  "aboard the Genesis Station",
  "aboard StarCylinder Epsilon",
  "in World of Warcraft",
  "while streaming on Twitch",
  "near the machine city",
  "near the nation of exiled robots",
  "on an interstellar colony craft",
  "in a junk heap",
  "in a derelict Soylent factory",
  "in a robotic robot factory factory",
  "between the six worlds",
  "at the edge of known space",
  "at the event horizon of a black hole",
  "inside a black hole",
  "inside a net paradox",
  "aboard the Skyforge",
  "on Sealand",
  "in the Coreforge",
  "aboard a space elevator",
  "at a classified location",
  "at a classified facility",
  "at a research facility",
  "at a research outpost",
  "at a sky hotel",
  "in onion space",
  "in Upper Taipei",
  "at the World Capital",
  "inside a world engine",
  "from a secret base",
  "in a secret lair",
  "on Isla Nublar",
  "on the Shadow Wastes",
  "on the Dreadplains",
  "at a Budapest hotel",
  "in the mind of the Prime Autarch",
  "at Jackpoint Six-Four",
  "at the Darknet Exchange",
  "at a rogue data haven",
  "aboard a floating libertarian island",
  "at a Congolese server megafarm",
  "in the Neutral Zone",
  "in the Armistice Zone",
  "in the Protected Zone",
  "in the Forbidden Zone",
  "in the Watcher's Domain",
  "in the Sixth Fury",
  "at a Bitcoin mining colony",
  "on an asteroid colony",
  "at an illegal Bitcoin production dungeon",
  "at the Black Sun",
  "in Greater Hong Kong",
  "in the eye of a nebula hurricane",
  "at Express Port 142",
  "at Express Port 81",
  "at Express Port 9",
  "at Local Port 13",
  "at Local Port 55",
  "at Local Port 223",
  "on the Supranet",
  "on the Subnet",
  "in the Googleverse",
  "in the Matrix",
  "in NeurOceania",
  "in central ExoPakistan",
  "in Third Zealand",
  "in ReSpain",
  "in New Angeles",
  "in Night City",
  "in the Twelfth French Republic",
  "in Omni-Iceland",
  "in Mega-Outer Mongolia",
  "between the Twin Void Terrors",
  "close to Holding Sector MV-7",
  "at Echo Station 3T8",
  "at an Automated Factory",
  "in the Netsphere",
  "at a Tibanna gas colony",
  "on Level 1313"
];
